'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Candidato
    Public Property ID_Candidato As Integer
    Public Property tb_Candidatos_nombres As String
    Public Property tb_Candidatos_apellidos As Byte()
    Public Property tb_Candidatos_genero As Nullable(Of Boolean)
    Public Property tb_Candidatos_cedula As String
    Public Property tb_Candidatos_fecNac As Nullable(Of Date)
    Public Property tb_Candidatos_estadoCivil As String
    Public Property tb_Candidatos_domicilio As String
    Public Property tb_Candidatos_ciudad As String
    Public Property tb_Candidatos_departamento As String
    Public Property tb_Candidatos_pais As String
    Public Property tb_Candidatos_telefonoConv As String
    Public Property tb_Candidatos_telefonomovil As String
    Public Property tb_Candidatos_correoElectronico As String
    Public Property tb_Candidatos_especialidad As Nullable(Of Integer)
    Public Property tb_Candidatos_idioma As Nullable(Of Integer)
    Public Property tb_Candidatos_nivelAcademico As String
    Public Property tb_Candidatos_notaTestPsicologico As Nullable(Of Double)
    Public Property tb_Candidatos_notaTestPsicometrico As Nullable(Of Double)
    Public Property tb_Candidatos_notaTestTecnico As Nullable(Of Double)

    Public Overridable Property Especialidade As Especialidade
    Public Overridable Property Idioma As Idioma

End Class
