'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class capacitacion
    Public Property ID As Integer
    Public Property ID_plan As Integer
    Public Property nombre As String
    Public Property fecha As Date
    Public Property duracion As Integer
    Public Property ID_centro_cap As Integer
    Public Property ID_area As Integer

    Public Overridable Property area As area
    Public Overridable Property centro_capacit As centro_capacit
    Public Overridable Property plan_estudio As plan_estudio
    Public Overridable Property Empleado As ICollection(Of Empleado) = New HashSet(Of Empleado)

End Class
