'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cargo
    Public Property Id_Cargo As Integer
    Public Property Nombre_Cargo As String
    Public Property Salario As Integer
    Public Property Descripcion As String
    Public Property Id_Oficina As Nullable(Of Integer)

    Public Overridable Property Empleado As ICollection(Of Empleado) = New HashSet(Of Empleado)
    Public Overridable Property Oficina As Oficina
    Public Overridable Property Contrato As ICollection(Of Contrato) = New HashSet(Of Contrato)

End Class
