'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Contrato
    Public Property Id_Contrato As Integer
    Public Property Fecha_Contratacion As Nullable(Of Date)
    Public Property Fecha_Fin As Nullable(Of Date)
    Public Property Id_Empleado As Nullable(Of Integer)
    Public Property Id_Documento As Nullable(Of Integer)
    Public Property Id_Cargo As Nullable(Of Integer)

    Public Overridable Property Cargo As Cargo
    Public Overridable Property Documentacion As Documentacion
    Public Overridable Property Empleado As Empleado

End Class
