'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Debilidades
    Public Property Nombre_Debilidades As String

    Public Overridable Property Resultados_Evaluacion As ICollection(Of Resultados_Evaluacion) = New HashSet(Of Resultados_Evaluacion)

End Class
