'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetEspecialidadesCand
    Public Property Id_DetalleEspecialistaCandidato As Integer
    Public Property tb_DetEspeCan_titulo As String
    Public Property tb_DetEspeCan_aniosExpe As Nullable(Of Integer)

    Public Overridable Property Especialidades As ICollection(Of Especialidade) = New HashSet(Of Especialidade)

End Class
