'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetEspecialidadesReq
    Public Property ID_EspecialidadesReq As Integer
    Public Property tb_DetEspecialidadesReq_titulo As String
    Public Property tb_DetespecialidadesReq_aniosExp As Nullable(Of Integer)

    Public Overridable Property EspecialidadesReqs As ICollection(Of EspecialidadesReq) = New HashSet(Of EspecialidadesReq)

End Class
