'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetIdiomasCand
    Public Property ID_DetCandidatosIdioma As Integer
    Public Property tb_DetIdiCan_idioma As String
    Public Property tb_DetIdiCan_dominio As Nullable(Of Double)

    Public Overridable Property Idiomas As ICollection(Of Idioma) = New HashSet(Of Idioma)

End Class
