'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Documentacion
    Public Property Id_Documento As Integer
    Public Property Tipo_Documento As String
    Public Property Descripcion As String

    Public Overridable Property Contrato As ICollection(Of Contrato) = New HashSet(Of Contrato)

End Class
