'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class empleado
    Public Property id As Integer
    Public Property primer_nombre As String
    Public Property apellidos As String
    Public Property cedula As String
    Public Property telefono As String
    Public Property fecha_contratacion As Date
    Public Property vacaciones_acumuladas As Double
    Public Property fecha_creacion As Date
    Public Property cargo As String
    Public Property departamento As String
    Public Property salario As Double
    Public Property inss As String
    Public Property timestamp As Byte()

    Public Overridable Property entradas As ICollection(Of entrada) = New HashSet(Of entrada)
    Public Overridable Property liquidaciones As ICollection(Of liquidacione) = New HashSet(Of liquidacione)
    Public Overridable Property permisos As ICollection(Of permiso) = New HashSet(Of permiso)
    Public Overridable Property salidas As ICollection(Of salida) = New HashSet(Of salida)
    Public Overridable Property vacaciones As ICollection(Of vacacione) = New HashSet(Of vacacione)

End Class
