'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleado
    Public Property Id_Empleado As Integer
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Cedula As String
    Public Property Telefono As String
    Public Property FechaNacimiento As Date
    Public Property Estado_Civil As Boolean
    Public Property Domicilio As String
    Public Property Estado As Boolean
    Public Property Id_Profesion As Integer
    Public Property Id_area As Integer
    Public Property Id_Cargo As Integer

    Public Overridable Property Contrato As ICollection(Of Contrato) = New HashSet(Of Contrato)
    Public Overridable Property permisos As ICollection(Of permisos) = New HashSet(Of permisos)
    Public Overridable Property vacaciones As ICollection(Of vacaciones) = New HashSet(Of vacaciones)

End Class
