'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EspecialidadesReq
    Public Property tb_EspecialidadesReq_id As Integer
    Public Property ID_DetalleEspecReq As Nullable(Of Integer)

    Public Overridable Property DetEspecialidadesReq As DetEspecialidadesReq
    Public Overridable Property Vacantes As ICollection(Of Vacantes) = New HashSet(Of Vacantes)

End Class
