'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Especialidade
    Public Property Id_Especialidad As Integer
    Public Property DetalleEspecialidad As Nullable(Of Integer)

    Public Overridable Property Candidatoes As ICollection(Of Candidato) = New HashSet(Of Candidato)
    Public Overridable Property DetEspecialidadesCand As DetEspecialidadesCand

End Class
