'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Fortaleza
    Public Property Id_Fortalezas As Integer
    Public Property Nombre_Fortalezas As String

    Public Overridable Property Indicadores As ICollection(Of Indicadore) = New HashSet(Of Indicadore)

End Class
