'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IdiomasRequerido
    Public Property tb_idiomasReq_id As Integer
    Public Property ID_DetalleIdiomaReq As Nullable(Of Integer)

    Public Overridable Property DetIdiomasReq As DetIdiomasReq
    Public Overridable Property Vacantes As ICollection(Of Vacante) = New HashSet(Of Vacante)

End Class
