'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Idiomas
    Public Property tb_idiomas_id As Integer
    Public Property DetalleIdiomaCandidato As Nullable(Of Integer)

    Public Overridable Property Candidato As ICollection(Of Candidato) = New HashSet(Of Candidato)
    Public Overridable Property DetIdiomasCand As DetIdiomasCand

End Class
