'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Indicadore
    Public Property Id_Indicador As Integer
    Public Property Nombre_Indicador As String
    Public Property Id_Nivel_Evaluativo As Integer
    Public Property Id_Fortalezas As Integer
    Public Property Id_Debilidades As Integer
    Public Property Fecha_Evaluacion As Date

    Public Overridable Property Debilidade As Debilidade
    Public Overridable Property Fortaleza As Fortaleza
    Public Overridable Property Niveles_Evaluativos As Niveles_Evaluativos
    Public Overridable Property Resultados As ICollection(Of Resultado) = New HashSet(Of Resultado)

End Class
