'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class liquidacione
    Public Property id As Integer
    Public Property id_emp As Integer
    Public Property fecha_egreso As Date
    Public Property fecha_creacion As Date
    Public Property total_aguinaldo As Double
    Public Property total_vacaciones As Double
    Public Property total_indemnizacion As Double
    Public Property total_salarios_restantes As Double
    Public Property deduccion_inss As Double
    Public Property deduccion_prestamo_personales As Double
    Public Property deduccion_otros As Double
    Public Property descripcion_otros As String
    Public Property pago_total As Double
    Public Property timestamp As Byte()

    Public Overridable Property empleado As empleado

End Class
