'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DB_Recursos_HumanosEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DB_Recursos_HumanosEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Antecedentes() As DbSet(Of Antecedente)
    Public Overridable Property areas() As DbSet(Of area)
    Public Overridable Property Candidatoes() As DbSet(Of Candidato)
    Public Overridable Property capacitacions() As DbSet(Of capacitacion)
    Public Overridable Property Cargoes() As DbSet(Of Cargo)
    Public Overridable Property centro_capacit() As DbSet(Of centro_capacit)
    Public Overridable Property Contratoes() As DbSet(Of Contrato)
    Public Overridable Property Debilidades() As DbSet(Of Debilidade)
    Public Overridable Property DetEspecialidadesCands() As DbSet(Of DetEspecialidadesCand)
    Public Overridable Property DetEspecialidadesReqs() As DbSet(Of DetEspecialidadesReq)
    Public Overridable Property DetIdiomasCands() As DbSet(Of DetIdiomasCand)
    Public Overridable Property DetIdiomasReqs() As DbSet(Of DetIdiomasReq)
    Public Overridable Property Documentacions() As DbSet(Of Documentacion)
    Public Overridable Property Empleadoes() As DbSet(Of Empleado)
    Public Overridable Property encuestas() As DbSet(Of encuesta)
    Public Overridable Property entradas() As DbSet(Of entrada)
    Public Overridable Property Especialidades() As DbSet(Of Especialidade)
    Public Overridable Property EspecialidadesReqs() As DbSet(Of EspecialidadesReq)
    Public Overridable Property Fortalezas() As DbSet(Of Fortaleza)
    Public Overridable Property Idiomas() As DbSet(Of Idioma)
    Public Overridable Property IdiomasRequeridos() As DbSet(Of IdiomasRequerido)
    Public Overridable Property Indicadores() As DbSet(Of Indicadore)
    Public Overridable Property Informacion_Academica() As DbSet(Of Informacion_Academica)
    Public Overridable Property liquidaciones() As DbSet(Of liquidacione)
    Public Overridable Property Niveles_Evaluativos() As DbSet(Of Niveles_Evaluativos)
    Public Overridable Property Oficinas() As DbSet(Of Oficina)
    Public Overridable Property permisos() As DbSet(Of permiso)
    Public Overridable Property plan_estudio() As DbSet(Of plan_estudio)
    Public Overridable Property preguntas() As DbSet(Of pregunta)
    Public Overridable Property Profesiones() As DbSet(Of Profesione)
    Public Overridable Property respuestas() As DbSet(Of respuesta)
    Public Overridable Property Resultados() As DbSet(Of Resultado)
    Public Overridable Property salidas() As DbSet(Of salida)
    Public Overridable Property TB_Adm_Contenido() As DbSet(Of TB_Adm_Contenido)
    Public Overridable Property TB_Adm_OpcionesSistema() As DbSet(Of TB_Adm_OpcionesSistema)
    Public Overridable Property TB_Adm_RolesDeUsuario() As DbSet(Of TB_Adm_RolesDeUsuario)
    Public Overridable Property TB_Adm_Sesion() As DbSet(Of TB_Adm_Sesion)
    Public Overridable Property TB_Adm_Usuario() As DbSet(Of TB_Adm_Usuario)
    Public Overridable Property TB_Adm_Usuario_OpcionesSistema() As DbSet(Of TB_Adm_Usuario_OpcionesSistema)
    Public Overridable Property TB_Adm_Usuario_Roles() As DbSet(Of TB_Adm_Usuario_Roles)
    Public Overridable Property TB_CUOTA() As DbSet(Of TB_CUOTA)
    Public Overridable Property TB_DEDUCCION() As DbSet(Of TB_DEDUCCION)
    Public Overridable Property TB_DEVENGADO() As DbSet(Of TB_DEVENGADO)
    Public Overridable Property TB_ESTADO() As DbSet(Of TB_ESTADO)
    Public Overridable Property TB_MOVIMIENTO_DEDUCCION() As DbSet(Of TB_MOVIMIENTO_DEDUCCION)
    Public Overridable Property TB_MOVIMIENTO_DEVENGADO() As DbSet(Of TB_MOVIMIENTO_DEVENGADO)
    Public Overridable Property TB_PLAZO_PAGO() As DbSet(Of TB_PLAZO_PAGO)
    Public Overridable Property TB_PRESTAMO() As DbSet(Of TB_PRESTAMO)
    Public Overridable Property TB_RECIBO_CUOTA() As DbSet(Of TB_RECIBO_CUOTA)
    Public Overridable Property temas() As DbSet(Of tema)
    Public Overridable Property tema_plan() As DbSet(Of tema_plan)
    Public Overridable Property vacaciones() As DbSet(Of vacacione)
    Public Overridable Property Vacantes() As DbSet(Of Vacante)

End Class
