'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DB_Recursos_HumanosEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DB_Recursos_HumanosEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Contrato() As DbSet(Of Contrato)
    Public Overridable Property Empleado() As DbSet(Of Empleado)
    Public Overridable Property permisos() As DbSet(Of permisos)
    Public Overridable Property vacaciones() As DbSet(Of vacaciones)

End Class
