'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Niveles_Evaluativos
    Public Property Id_Nivel_Evaluativo As Integer
    Public Property Tipo_Nivel_Evaluativo As String

    Public Overridable Property Indicadores As ICollection(Of Indicadores) = New HashSet(Of Indicadores)

End Class
