'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class plan_estudio
    Public Property ID As Integer
    Public Property ID_tema_plan As Integer
    Public Property anio As String

    Public Overridable Property capacitacions As ICollection(Of capacitacion) = New HashSet(Of capacitacion)
    Public Overridable Property tema_plan As tema_plan

End Class
