'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pregunta
    Public Property ID As Integer
    Public Property pregunta1 As String

    Public Overridable Property encuestas As ICollection(Of encuesta) = New HashSet(Of encuesta)
    Public Overridable Property respuestas As ICollection(Of respuesta) = New HashSet(Of respuesta)

End Class
