'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class respuesta
    Public Property ID As Integer
    Public Property ID_pregunta As Integer
    Public Property respuesta1 As String
    Public Property correcta As Integer

    Public Overridable Property pregunta As pregunta

End Class
