'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Resultado
    Public Property Id_Resultados As Integer
    Public Property Id_Indicador As Integer
    Public Property Resultado_Final As String
    Public Property Id_Empleado As Integer

    Public Overridable Property Empleado As Empleado
    Public Overridable Property Indicadore As Indicadore

End Class
