'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Resultados_Evaluacion
    Public Property Numero_Evaluacion As Nullable(Of Integer)
    Public Property Id_Empleado As Integer
    Public Property Nombre_Indicador As String
    Public Property Tipo_Nivel_Evaluativo As String
    Public Property Nombre_Fortalezas As String
    Public Property Nombre_Debilidades As String
    Public Property Fecha_Evaluacion As String
    Public Property Nota_Indicador As Nullable(Of Integer)
    Public Property Total_Evaluacion As Nullable(Of Integer)
    Public Property Observaciones As String
    Public Property cod As Nullable(Of Integer)

    Public Overridable Property Debilidades As Debilidades
    Public Overridable Property Empleado As Empleado
    Public Overridable Property Fortalezas As Fortalezas
    Public Overridable Property Indicadores As Indicadores
    Public Overridable Property Niveles_Evaluativos As Niveles_Evaluativos

End Class
