'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_Adm_Contenido
    Public Property id_contenido As Short
    Public Property id_sesion As Short
    Public Property id_user As Short
    Public Property tabla_registro As String
    Public Property registros_creados As String
    Public Property tabla_cambios As String
    Public Property cambios_realizados As String

    Public Overridable Property TB_Adm_Sesion As TB_Adm_Sesion
    Public Overridable Property TB_Adm_Usuario As TB_Adm_Usuario

End Class
