'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_Adm_Usuario
    Public Property id_user As Short
    Public Property Id_Empleado As Integer
    Public Property nombre As String
    Public Property passUser As String

    Public Overridable Property Empleado As Empleado
    Public Overridable Property TB_Adm_Contenido As ICollection(Of TB_Adm_Contenido) = New HashSet(Of TB_Adm_Contenido)
    Public Overridable Property TB_Adm_Sesion As ICollection(Of TB_Adm_Sesion) = New HashSet(Of TB_Adm_Sesion)
    Public Overridable Property TB_Adm_Usuario_OpcionesSistema As ICollection(Of TB_Adm_Usuario_OpcionesSistema) = New HashSet(Of TB_Adm_Usuario_OpcionesSistema)
    Public Overridable Property TB_Adm_Usuario_Roles As ICollection(Of TB_Adm_Usuario_Roles) = New HashSet(Of TB_Adm_Usuario_Roles)

End Class
