'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_Adm_Usuario_Roles
    Public Property id_userRoles As Integer
    Public Property id_user As Integer
    Public Property id_rolUsuario As Integer

    Public Overridable Property TB_Adm_RolesDeUsuario As TB_Adm_RolesDeUsuario
    Public Overridable Property TB_Adm_Usuario As TB_Adm_Usuario

End Class
