'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_Adm_RolesDeUsuario
    Public Property id_rolUsuario As Integer
    Public Property rol_usuario As String
    Public Property descripcion_rol As String
    Public Property moduloRol As String

    Public Overridable Property TB_Adm_Usuario_Roles As ICollection(Of TB_Adm_Usuario_Roles) = New HashSet(Of TB_Adm_Usuario_Roles)

End Class
