'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_Adm_Usuario_OpcionesSistema
    Public Property id_userOpciones As Short
    Public Property id_user As Short
    Public Property id_opciones As Short

    Public Overridable Property TB_Adm_OpcionesSistema As TB_Adm_OpcionesSistema
    Public Overridable Property TB_Adm_Usuario As TB_Adm_Usuario

End Class
