'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_Adm_OpcionesSistema
    Public Property id_opciones As Short
    Public Property nombre_opciones As String
    Public Property desc_opciones As String
    Public Property modulo As String

    Public Overridable Property TB_Adm_Usuario_OpcionesSistema As ICollection(Of TB_Adm_Usuario_OpcionesSistema) = New HashSet(Of TB_Adm_Usuario_OpcionesSistema)

End Class
