'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_Adm_Bitacora_Transaccional
    Public Property id_bitacora_transaccional As Integer
    Public Property id_sesion As String
    Public Property usuario As String
    Public Property Tipo_Registro As String
    Public Property Tabla_Asociada As String
    Public Property Identificador_Registro As String
    Public Property Campos As String
    Public Property Antiguos_Registros As String
    Public Property Nuevos_Registros As String
    Public Property Fecha As Nullable(Of Date)

End Class
