'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_Adm_Sesion
    Public Property id_sesion As Short
    Public Property id_user As Short
    Public Property fechaSesion As Date
    Public Property horaIngreso As Date
    Public Property horaFinalizado As Date

    Public Overridable Property TB_Adm_Contenido As ICollection(Of TB_Adm_Contenido) = New HashSet(Of TB_Adm_Contenido)
    Public Overridable Property TB_Adm_Usuario As TB_Adm_Usuario

End Class
