'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_CUOTA
    Public Property id_cuota As Integer
    Public Property fecha_pago As Date
    Public Property numero_cuota As Integer
    Public Property monto_cuota As Double
    Public Property id_prestamo As Integer
    Public Property id_estado As Integer

    Public Overridable Property TB_PRESTAMO As TB_PRESTAMO
    Public Overridable Property TB_RECIBO_CUOTA As ICollection(Of TB_RECIBO_CUOTA) = New HashSet(Of TB_RECIBO_CUOTA)

End Class
