'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_MOVIMIENTO_DEVENGADO
    Public Property ID As Integer
    Public Property EMPLEADO As Integer
    Public Property AÑO As Integer
    Public Property MES As Integer
    Public Property DIA_INICIO As Integer
    Public Property DIA_FIN As Integer
    Public Property MONTO As Decimal
    Public Property ID_DEVENGADOS As Integer

    Public Overridable Property Empleado1 As Empleado
    Public Overridable Property TB_DEVENGADO As TB_DEVENGADO

End Class
