'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_PLAZO_PAGO
    Public Property id_plazo_pago As Integer
    Public Property plazo_pago As String
    Public Property cant_plazo As Integer

    Public Overridable Property TB_PRESTAMO As ICollection(Of TB_PRESTAMO) = New HashSet(Of TB_PRESTAMO)
    Public Overridable Property TB_PRESTAMO1 As ICollection(Of TB_PRESTAMO) = New HashSet(Of TB_PRESTAMO)

End Class
