'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_RECIBO_CUOTA
    Public Property id_prestamo As Integer
    Public Property id_cuota As Integer
    Public Property fecha_pago_emitido As Date
    Public Property ciudad_emitido As Integer
    Public Property Id_Empleado As Integer

    Public Overridable Property Empleado As Empleado
    Public Overridable Property TB_CUOTA As TB_CUOTA
    Public Overridable Property TB_PRESTAMO As TB_PRESTAMO

End Class
