'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tema_plan
    Public Property ID_plan As Integer
    Public Property ID_tema As Integer

    Public Overridable Property plan_estudio As ICollection(Of plan_estudio) = New HashSet(Of plan_estudio)
    Public Overridable Property tema As tema

End Class
