'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tema
    Public Property ID As Integer
    Public Property nombre As String

    Public Overridable Property tema_plan As ICollection(Of tema_plan) = New HashSet(Of tema_plan)

End Class
