'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vacantes
    Public Property tb_Vacante_id As Integer
    Public Property tb_Vacantes_cargo As String
    Public Property tb_Vacantes_genero As String
    Public Property tb_Vacantes_edadMax As Nullable(Of Integer)
    Public Property tb_Vacantes_edadMin As Nullable(Of Integer)
    Public Property tb_Vacantes_ofertaSal As Nullable(Of Double)
    Public Property tb_Vacantes_nivelAcade As String
    Public Property tb_Vacantes_idioma As Nullable(Of Integer)
    Public Property tb_Vacantes_especialidad As Nullable(Of Integer)
    Public Property tb_Vacantes_notaMinTestPsicologico As Nullable(Of Double)
    Public Property tb_Vacantes_notaMinTestPsicometrico As Nullable(Of Double)
    Public Property tb_Vacantes_notaMinTestTecnico As Nullable(Of Double)

    Public Overridable Property EspecialidadesReq As EspecialidadesReq
    Public Overridable Property IdiomasRequeridos As IdiomasRequeridos

End Class
