'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vacacione
    Public Property id As Integer
    Public Property id_emp As Integer
    Public Property fecha_creacion As Date
    Public Property fecha_inicio As Date
    Public Property fecha_fin As Date
    Public Property aceptado As Boolean
    Public Property timestamp As Byte()

    Public Overridable Property empleado As empleado

End Class
