'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VW_DIAS_TRABAJO_EMP
    Public Property EMPLEADO As Integer
    Public Property FECHA As Date
    Public Property TOTAL_HORAS As Nullable(Of Integer)
    Public Property TOTAL_HORAS_EXTRA As Nullable(Of Integer)
    Public Property TOTAL_HORAS_AUSENTE As Nullable(Of Integer)
    Public Property HORAS_PERMISO As Integer
    Public Property FECHA_INTEGRACION As Nullable(Of Date)
    Public Property TITULO As String
    Public Property SALARIO_HORA As Integer
    Public Property NOMBRE As String
    Public Property APELLIDO As String

End Class
