'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VW_EMP
    Public Property ID As Integer
    Public Property FECHA_INTEGRACION As Nullable(Of Date)
    Public Property SALARIO_HORA As Integer
    Public Property TITULO As String
    Public Property NOMBRE As String
    Public Property APELLIDO As String
    Public Property TELEFONO As String
    Public Property DIRECCION As String

End Class
