'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VW_ENTRADA_SALIDA
    Public Property EMPLEADO As Integer
    Public Property FECHA As Date
    Public Property TOTAL_HORAS As Nullable(Of Integer)
    Public Property HORAS_EXTRA As Nullable(Of Integer)
    Public Property HORAS_AUSENTE As Nullable(Of Integer)

End Class
