'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VW_NOMINA
    Public Property EMPLEADO As Integer
    Public Property AÑO As Nullable(Of Integer)
    Public Property MES As Nullable(Of Integer)
    Public Property DIA_INICIO As Integer
    Public Property DIA_FIN As Nullable(Of Integer)
    Public Property FECHA_INTEGRACION As Nullable(Of Date)
    Public Property TITULO As String
    Public Property SALARIO_HORA As Integer
    Public Property NOMBRE As String
    Public Property APELLIDO As String
    Public Property TOTAL_HORAS_TRABAJADAS As Nullable(Of Integer)
    Public Property TOTAL_HORAS_EXTRA As Nullable(Of Integer)
    Public Property TOTAL_HORAS_AUSENTE As Nullable(Of Integer)
    Public Property TOTAL_HORAS_PERMISO As Nullable(Of Integer)
    Public Property TOTAL_DIAS_VACACIONES As Integer
    Public Property SALARIO_BASE As Nullable(Of Integer)
    Public Property IR As Nullable(Of Integer)
    Public Property INSS As Nullable(Of Decimal)
    Public Property AGUINALDO As Nullable(Of Decimal)
    Public Property TOTAL_PRESTAMOS As Double
    Public Property MOVIMIENTOS_DEVENGADOS As Decimal
    Public Property MOVIMIENTOS_DEDUCCIONES As Decimal
    Public Property TOTAL_DEVENGADOS As Nullable(Of Decimal)
    Public Property TOTAL_DEDUCCIONES As Nullable(Of Double)
    Public Property PAGO_NETO As Nullable(Of Double)

End Class
