'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VW_Permisos
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Cedula As String
    Public Property fecha_inicio As Date
    Public Property fecha_fin As Date
    Public Property descripcion As String
    Public Property categoria As String

End Class
