'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VW_Vacaciones
    Public Property Id_Empleado As Integer
    Public Property Nombre As String
    Public Property Apellido As String
    Public Property Cedula As String
    Public Property Fecha_Contratacion As Nullable(Of Date)
    Public Property fecha_inicio As Date
    Public Property fecha_fin As Date
    Public Property pagado As Boolean
    Public Property Debidato As Nullable(Of Integer)

End Class
